# Generated by Django 2.2.5 on 2019-09-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190915_0633'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email',)},
        ),
    ]
