# Generated by Django 2.2.5 on 2019-09-13 18:52

import apps.books.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_ts', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('name', models.CharField(max_length=255, verbose_name='Book Title')),
                ('cover', models.ImageField(upload_to=apps.books.models.book_cover_path)),
                ('total_pages', models.IntegerField(blank=True, null=True)),
                ('author', models.ManyToManyField(related_name='books_written_set', related_query_name='book_writers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book',
                'db_table': 'eb_book',
            },
        ),
        migrations.CreateModel(
            name='UserReadingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_ts', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('page_no', models.IntegerField(default=1)),
                ('status', models.IntegerField(choices=[(1, 'Started'), (2, 'Halfway'), (3, 'Finished')], default=1)),
                ('total_pages', models.IntegerField()),
                ('time_spent', models.TimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_read_set', to='books.Book')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_userreadinghistory_created_related', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_userreadinghistory_updated_related', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(limit_choices_to=apps.books.models.limit_user_choices, on_delete=django.db.models.deletion.CASCADE, related_name='books_readed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Reading History',
                'db_table': 'eb_user_reading_history',
            },
        ),
        migrations.CreateModel(
            name='UserBookSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_ts', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_book_session_set', to='books.Book')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_userbooksessions_created_related', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_userbooksessions_updated_related', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(limit_choices_to=apps.books.models.limit_user_choices, on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Reading sessions',
                'db_table': 'eb_user_reading_sessions',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Category')),
            ],
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_ts', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('review', models.CharField(blank=True, max_length=2048, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reviews_set', to='books.Book')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_bookreview_created_related', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_bookreview_updated_related', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(limit_choices_to=apps.books.models.limit_user_choices, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book Reviews',
                'db_table': 'eb_book_reviews',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Category'),
        ),
        migrations.AddField(
            model_name='book',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_book_created_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_book_updated_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterOrderWithRespectTo(
            name='book',
            order_with_respect_to='name',
        ),
    ]
