# Generated by Django 2.2.5 on 2019-09-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookreview',
            options={'verbose_name': 'Book Review'},
        ),
    ]
