# Generated by Django 2.2.5 on 2019-09-16 17:22

import apps.books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190915_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(default='books', upload_to=apps.books.models.get_dir_path),
            preserve_default=False,
        ),
    ]
